version: "3.8"

services:
  server:
    build:
      context: ./backend # Docker will look in the backend folder for the Dockerfile to build this image.
    ports:
      - "5002:5002"
    environment:
      # - MONGO_URI=mongodb://mongo:27017/BlogApp
      # - MONGO_URI=${MONGO_URI}
      - NODE_ENV=development
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    restart: always

  client:
    build:
      context: ./frontend
    ports:
      - "5173:5173" # map same port for Vite dev server
    volumes:
      - ./frontend:/app # mount local code into container for hot reload
      - /app/node_modules # prevent overwriting node_modules from host
    command: [ "npm", "run", "dev", "--", "--host", "0.0.0.0" ]
    restart: always

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
